pipeline {
    agent any

    stages {
        stage('Build') {
            steps {
                // get some code from GitHub
                git clone 'git@github.com:JColamaio/go-webapp-sample.git'
            }
        }
    }
    stage('UAT') {
        steps {
            // Get some code from Github
           git clone 'git@github.com:JColamaio/go-webapp-sample.git'
        }
    }
}